options:
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _ARTIFACT_REPO: 'gs://zeus-artifacts/per-push-builds'

steps:
  - name: 'maven:3.8.4-eclipse-temurin-17-alpine'
    args: [ 'mvn', '-e', '-Dmaven.wagon.http.retryHandler.count=3', 'compile', 'test', 'package']

artifacts:
  objects:
    location: '${_ARTIFACT_REPO}'
    paths: ['./target/Z*.jar']