steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--recurse-submodules', 'https://github.com/Kovalevskyi-Academy/Zeus.git']
  - name: 'gcr.io/cloud-builders/git'
    args: ['checkout', '$COMMIT_SHA']
    dir: 'Zeus'
  - name: 'maven:3.6.3-openjdk-15'
    args: ['mvn', 'compile']
    dir: 'Zeus'
  - name: 'maven:3.6.3-openjdk-15'
    args: [ 'mvn', 'test' ]
    dir: 'Zeus'
  - name: 'maven:3.6.3-openjdk-15'
    args: [ 'mvn', 'package' ]
    dir: 'Zeus'
  - name: 'maven:3.6.3-openjdk-15'
    args: [ 'mvn', 'deploy' ]
    dir: 'Zeus'